// flow-typed signature: 7d693fcd258473de86327595c9369eaa
// flow-typed version: <<STUB>>/@sentry/browser_v4.5.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sentry/browser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sentry/browser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@sentry/browser/build/bundle' {
  declare module.exports: any;
}

declare module '@sentry/browser/build/bundle.min' {
  declare module.exports: any;
}

declare module '@sentry/browser/dist/index' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/backend' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/client' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/index' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/integrations/breadcrumbs' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/integrations/globalhandlers' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/integrations/helpers' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/integrations/index' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/integrations/linkederrors' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/integrations/pluggable/ember' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/integrations/pluggable/reportingobserver' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/integrations/pluggable/vue' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/integrations/trycatch' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/integrations/useragent' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/md5' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/parsers' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/sdk' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/tracekit' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/transports/base' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/transports/beacon' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/transports/fetch' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/transports/index' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/transports/xhr' {
  declare module.exports: any;
}

declare module '@sentry/browser/esm/version' {
  declare module.exports: any;
}

// Filename aliases
declare module '@sentry/browser/build/bundle.js' {
  declare module.exports: $Exports<'@sentry/browser/build/bundle'>;
}
declare module '@sentry/browser/build/bundle.min.js' {
  declare module.exports: $Exports<'@sentry/browser/build/bundle.min'>;
}
declare module '@sentry/browser/dist/index.js' {
  declare module.exports: $Exports<'@sentry/browser/dist/index'>;
}
declare module '@sentry/browser/esm/backend.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/backend'>;
}
declare module '@sentry/browser/esm/client.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/client'>;
}
declare module '@sentry/browser/esm/index.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/index'>;
}
declare module '@sentry/browser/esm/integrations/breadcrumbs.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations/breadcrumbs'>;
}
declare module '@sentry/browser/esm/integrations/globalhandlers.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations/globalhandlers'>;
}
declare module '@sentry/browser/esm/integrations/helpers.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations/helpers'>;
}
declare module '@sentry/browser/esm/integrations/index.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations/index'>;
}
declare module '@sentry/browser/esm/integrations/linkederrors.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations/linkederrors'>;
}
declare module '@sentry/browser/esm/integrations/pluggable/ember.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations/pluggable/ember'>;
}
declare module '@sentry/browser/esm/integrations/pluggable/reportingobserver.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations/pluggable/reportingobserver'>;
}
declare module '@sentry/browser/esm/integrations/pluggable/vue.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations/pluggable/vue'>;
}
declare module '@sentry/browser/esm/integrations/trycatch.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations/trycatch'>;
}
declare module '@sentry/browser/esm/integrations/useragent.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/integrations/useragent'>;
}
declare module '@sentry/browser/esm/md5.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/md5'>;
}
declare module '@sentry/browser/esm/parsers.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/parsers'>;
}
declare module '@sentry/browser/esm/sdk.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/sdk'>;
}
declare module '@sentry/browser/esm/tracekit.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/tracekit'>;
}
declare module '@sentry/browser/esm/transports/base.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/transports/base'>;
}
declare module '@sentry/browser/esm/transports/beacon.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/transports/beacon'>;
}
declare module '@sentry/browser/esm/transports/fetch.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/transports/fetch'>;
}
declare module '@sentry/browser/esm/transports/index.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/transports/index'>;
}
declare module '@sentry/browser/esm/transports/xhr.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/transports/xhr'>;
}
declare module '@sentry/browser/esm/version.js' {
  declare module.exports: $Exports<'@sentry/browser/esm/version'>;
}
