// flow-typed signature: 3434dafbe8393bee0a8c757095611d92
// flow-typed version: <<STUB>>/next-seo_v1.8.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-seo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-seo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-seo/dist/index' {
  declare module.exports: any;
}

declare module 'next-seo/dist/jsonld/article' {
  declare module.exports: any;
}

declare module 'next-seo/dist/jsonld/blog' {
  declare module.exports: any;
}

declare module 'next-seo/dist/jsonld/breadcrumb' {
  declare module.exports: any;
}

declare module 'next-seo/dist/jsonld/course' {
  declare module.exports: any;
}

declare module 'next-seo/dist/jsonld/localBusiness' {
  declare module.exports: any;
}

declare module 'next-seo/dist/jsonld/logo' {
  declare module.exports: any;
}

declare module 'next-seo/dist/jsonld/product' {
  declare module.exports: any;
}

declare module 'next-seo/dist/jsonld/socialProfile' {
  declare module.exports: any;
}

declare module 'next-seo/dist/meta/buildTags' {
  declare module.exports: any;
}

declare module 'next-seo/dist/meta/defaultSEO' {
  declare module.exports: any;
}

declare module 'next-seo/dist/utils/markup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next-seo/dist/index.js' {
  declare module.exports: $Exports<'next-seo/dist/index'>;
}
declare module 'next-seo/dist/jsonld/article.js' {
  declare module.exports: $Exports<'next-seo/dist/jsonld/article'>;
}
declare module 'next-seo/dist/jsonld/blog.js' {
  declare module.exports: $Exports<'next-seo/dist/jsonld/blog'>;
}
declare module 'next-seo/dist/jsonld/breadcrumb.js' {
  declare module.exports: $Exports<'next-seo/dist/jsonld/breadcrumb'>;
}
declare module 'next-seo/dist/jsonld/course.js' {
  declare module.exports: $Exports<'next-seo/dist/jsonld/course'>;
}
declare module 'next-seo/dist/jsonld/localBusiness.js' {
  declare module.exports: $Exports<'next-seo/dist/jsonld/localBusiness'>;
}
declare module 'next-seo/dist/jsonld/logo.js' {
  declare module.exports: $Exports<'next-seo/dist/jsonld/logo'>;
}
declare module 'next-seo/dist/jsonld/product.js' {
  declare module.exports: $Exports<'next-seo/dist/jsonld/product'>;
}
declare module 'next-seo/dist/jsonld/socialProfile.js' {
  declare module.exports: $Exports<'next-seo/dist/jsonld/socialProfile'>;
}
declare module 'next-seo/dist/meta/buildTags.js' {
  declare module.exports: $Exports<'next-seo/dist/meta/buildTags'>;
}
declare module 'next-seo/dist/meta/defaultSEO.js' {
  declare module.exports: $Exports<'next-seo/dist/meta/defaultSEO'>;
}
declare module 'next-seo/dist/utils/markup.js' {
  declare module.exports: $Exports<'next-seo/dist/utils/markup'>;
}
