// flow-typed signature: d4f2801b36b918c96c926f52e1462048
// flow-typed version: <<STUB>>/react-clipboard.js_v2.0.2/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-clipboard.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-clipboard.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-clipboard.js/dist/react-clipboard' {
  declare module.exports: any;
}

declare module 'react-clipboard.js/dist/react-clipboard.min' {
  declare module.exports: any;
}

declare module 'react-clipboard.js/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-clipboard.js/dist/react-clipboard.js' {
  declare module.exports: $Exports<'react-clipboard.js/dist/react-clipboard'>;
}
declare module 'react-clipboard.js/dist/react-clipboard.min.js' {
  declare module.exports: $Exports<'react-clipboard.js/dist/react-clipboard.min'>;
}
declare module 'react-clipboard.js/index' {
  declare module.exports: $Exports<'react-clipboard.js'>;
}
declare module 'react-clipboard.js/index.js' {
  declare module.exports: $Exports<'react-clipboard.js'>;
}
declare module 'react-clipboard.js/webpack.config.js' {
  declare module.exports: $Exports<'react-clipboard.js/webpack.config'>;
}
